project_id = "fbmphwihmfzbbyavgusl"

[functions.send-verification-email]
verify_jwt = false

[functions.calculate-carbon]
verify_jwt = true

[functions.generate-weekly-report]
verify_jwt = false

[functions.update-leaderboard]
verify_jwt = false

[functions.ai-chat]
verify_jwt = true

[functions.receipt-ocr]
verify_jwt = true